export const SET_AUTHENTIFICATION = "SET_AUTHENTIFICATION";
export const INCREMENT_ACTIONS_COUNT = "INCREMENT_ACTIONS_COUNT";
export const FETCH_PEOPLE_IN_SPACE_REQUEST_START =
  "FETCH_PEOPLE_IN_SPACE_REQUEST_START";
export const FETCH_PEOPLE_IN_SPACE_REQUEST_SUCCESS =
  "FETCH_PEOPLE_IN_SPACE_REQUEST_SUCCESS";
